### ISSUE TITLE
PHP version problem

### ISSUE THREAD

**Issue by milanche911** [tinkerun/tinkerun#3]
For some reason, tinkerun is referencing the old version of php. I've updated my PHP version with homebrew and set env variable but as you can see from the screenshot app is not referencing the right one. 

![tinkerun_screenshot](https://user-images.githubusercontent.com/7223320/113060128-8a919380-91b0-11eb-950c-dad0bcf4f6c0.png)

**Comment by billyct** [comment]
that's strange.

could you run `echo $SHELL` in the tinkerun's terminal, to let me know what kind of shell is running in the app?

do you install php7.3.24 via brew? how about `brew link php` again, and restart the tinkerun app

### PS
someday before I met a similar strange thing as you meet, I can't run docker in tinkerun, but I can run it in the terminal, then I found a line that said `If you come from bash you might have to change your $PATH.` in the top of my `.zshrc` file.

```
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
```

when I uncommented it, then everything work fine.

**Comment by milanche911** [comment]
Bingo! 😄 👏

![image](https://user-images.githubusercontent.com/7223320/113196508-e0734380-9263-11eb-8f11-25e42715a2dd.png)
