### ISSUE TITLE
增加复制连接的功能？

### ISSUE THREAD

**Issue by huangdijia** [tinkerun/tinkerun#38]
如题

**Comment by billyct** [comment]
下载最新版，右键可复制连接。

https://github.com/tinkerun/tinkerun/releases/tag/v0.2.7

**Comment by huangdijia** [comment]
谢谢！效率很高！

**Comment by huangdijia** [comment]
@billyct 能再增加 tab 支持不。

**Comment by billyct** [comment]
@huangdijia 你的意思是不是指多开几个 connection 么? 你是用 mac 么？mac 连上一个 connection 之后会关闭「connections 窗口」，你可以在 dock 中右键「show connections」重新打开进行连接

**Comment by huangdijia** [comment]
> @huangdijia 你的意思是不是指多开几个 connection 么? 你是用 mac 么？mac 连上一个 connection 之后会关闭「connections 窗口」，你可以在 dock 中右键「show connections」重新打开进行连接

多开窗口不方便切换，像Chrome浏览器一样，可以多个标签挺方便的
