### ISSUE TITLE
[Feature Request] Docker/Lando support

### ISSUE THREAD

**Issue by eminos** [tinkerun/tinkerun#41]
:)

**Comment by billyct** [comment]
@eminos do you mean connect to the Docker/Lando? 


for me, I'm using [laravel/sail](https://laravel.com/docs/8.x/sail#introduction), so I connect my application with the `sail tinker` command.

and you can also use command like `docker-compose exec fpm php artisan tinker` to connect it

<img width="400" src="https://user-images.githubusercontent.com/1612364/138468776-1feccdf6-8e7d-40d2-b28f-f0889f8eadf2.png" alt="sail"/>

**Comment by eminos** [comment]
Oh wow! It does work! Case closed I guess :)
