### ISSUE TITLE
Does tinkerun support multi line command?

### ISSUE THREAD

**Issue by anurat** [tinkerun/tinkerun#5]
I can run a query on single line command 

`StmasSocks::where('stkcod', 'LIKE', '%B01%')->get();
`
but when I try to format the query in multiline, it throws an error.

```
StmasSocks::where('stkcod', 'LIKE', '%B01%')
    ->get();
```
It would be really useful for a really long query to split into multiple lines, is it possible to do that?

**Comment by billyct** [comment]
check out the new version 😉

**Comment by anurat** [comment]
Thank you for quick response!

Tried it, I know I'll enjoy using this a lot!
