### ISSUE TITLE
multi line string problem

### ISSUE THREAD

**Issue by anurat** [tinkerun/tinkerun#8]
When I run an SQL string with multiple lines, for example,
```
DB::connection("socks")
->select("
SELECT COUNT(*)
FROM stcrd
WHERE ( docnum LIKE 'IV%' OR docnum LIKE 'HS%' )
AND docdat BETWEEN '2017-01-01' AND '2018-01-01'
");
```
I got an error

```
Illuminate\Database\QueryException with message 'SQLSTATE[42000]: 
Syntax error or access violation: 1064 You have an error in your SQL syntax; 
check the manual that corresponds to your MariaDB server version for the right syntax to use near
 '( docnum LIKE 'IV%' OR docnum LIKE 'HS%' )AND docdat BETWEEN '2017-01-01' AND
'2' at line 1 (SQL: SELECT COUNT(*)FROM stcrdWHERE ( docnum LIKE 'IV%' OR docnum
```
Notice that table name `stcrd` and `WHERE` clause concatenate without spaces.  
It seems like tinkerun remove all spaces and line feeds and result in SQL error.

**Comment by billyct** [comment]
Yes, you are right. 

I just simply remove the comments, spaces and then make them one line yet.
🤔 I think I need to rewrite the function to be like [`php_strip_whitespace`](https://www.php.net/manual/en/function.php-strip-whitespace.php). if I want to minify the code to one line.

and another choice is just simulate the input code to the tinker like 
```
DB::connection("socks")\
->select("\
SELECT COUNT(*)\
FROM stcrd\
WHERE ( docnum LIKE 'IV%' OR docnum LIKE 'HS%' )\
AND docdat BETWEEN '2017-01-01' AND '2018-01-01'\
");
```

**Comment by billyct** [comment]
I just leave the spaces, and everything works fine.
check out https://github.com/tinkerun/tinkerun/releases/tag/v0.1.4
